server {
    #listen 443 ssl;
    listen 80;
    server_name localhost;
    root /var/www/cybertown;

    index index.html index.php;

    access_log off;
    error_log  /var/log/nginx/error.log error;

    location /api {
        proxy_pass http://ct-api:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /assets {
    	try_files /spa$uri $uri/; 
    }

    location /externprotos {
    	try_files /spa/assets$uri $uri/;
    }

    location /places/ {
        alias /var/www/cybertown/spa/assets/worlds/;
    }

    location /cgi-bin/ {
        root /var/www/cybertown/spa/dist;
        default_type text/html;
    }

    location /socket.io {
        proxy_pass http://ct-api:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    location / {
        root /var/www/cybertown/spa/dist;
        try_files $uri $uri/ /index.html;
    }
}

